# Generated by Django 5.1.2 on 2024-12-31 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarparkType',
            fields=[
                ('carparktypeid', models.AutoField(primary_key=True, serialize=False)),
                ('carparktype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSystem',
            fields=[
                ('parksystemid', models.AutoField(primary_key=True, serialize=False)),
                ('typeofparkingsystem', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('carparkno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('x_coord', models.CharField(max_length=50)),
                ('y_coord', models.CharField(max_length=50)),
                ('shorttermparking', models.CharField(max_length=50)),
                ('freeparking', models.CharField(max_length=50)),
                ('nightparking', models.CharField(max_length=3)),
                ('carparkingdecks', models.IntegerField()),
                ('gantryheight', models.FloatField()),
                ('carparkbasement', models.CharField(max_length=1)),
                ('carparktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpark.carparktype')),
                ('parksystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpark.parkingsystem')),
            ],
        ),
    ]
